#
# Copyright (c) 2023 Clarence Zhou<zhou_chenz@163.com>.
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.
#

string req
---
string rig